[Interface]
Address = 10.255.0.23
PrivateKey = +MffCSrH2+aypPc+S1RS90FCGbR9KXfaZvTUNyCj6mo=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = 7B1635LAf87npTP2Es3NAZDenMFVoItqKYgQ0d6OEXk=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
