[Interface]
Address = 10.255.0.46
PrivateKey = SCcixekyziTgTsIpICGv4ZYc7XqINbCXoJaGzvA4NWk=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = MCjs8Y5+VwFJEKdeVwxZ5jJ6kGhDuO8a5oxdG7bQpQg=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
