[Interface]
Address = 10.255.0.18
PrivateKey = eC9hmcXWC460pE/dFUWrwXxnWzbS7ArA+1zZs2QvgHY=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = x0rKOPSCuY2G20Jst2o+knCHzPCHzN2yP9usPN+QIVk=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
