[Interface]
Address = 10.255.0.38
PrivateKey = oCrDxWJV7JptsVa1GB/qjEC3uztJvl4bG1Ax6/8dJlI=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = wtprdKNCgDvOSmCdCsD2AqNFssUa2qU6kW5q8yX2AqU=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
