[Interface]
Address = 10.255.0.22
PrivateKey = MByXF3/JVZ4+UR+UslXQbjquQ5cWqm4kIkqooBG3gXo=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = LcKZY3gULht6YMcD6F6sLlY7DMhA6r2eqraGcHZXCAo=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
