[Interface]
Address = 10.255.0.30
PrivateKey = 4GTENF/WIhGv7EmKgcWorvvnQlAC6+w3PXvUoKQfNFs=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = +zSt5+ju1y9HDdVAj0jvYfpqi9BHgt42+ZCBJV3ePs8=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
