[Interface]
Address = 10.255.0.13
PrivateKey = QHR0xcCqX4dGYeyunxwDNZKlkI20cgH5+OvSs7y0/kA=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = 5zEcnpLq0AgsIuK2SNDOd3HbcQkar1YM1+0pN+soA6k=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
