[Interface]
Address = 10.255.0.17
PrivateKey = mEa1d7eTs5LWlr/5R/8AYUKx7lnMngTT0zF3/+pAW08=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = feL4b2E0YMApf3iyQo/8h3cAGde282TbkS/xnfTmQ3o=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
