[Interface]
Address = 10.255.0.5
PrivateKey = UKfZ0TpvSAxBNO9SMIDd4nT6ChCHDCh5BuHEGbI9hk4=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = LwZh6IeE3XWC4gR5wgAQVZRYt29IGbgE0kt9YyuOI+4=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
