[Interface]
Address = 10.255.0.51
PrivateKey = 4Pn2xJRVJazWC9zBX3pi63cvc+xMFYImyrsVHZSf0no=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = Xqo7Ugy60ldqmA9RbfRqt1vmDl5j/b8xRh5iW0on5ow=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
