[Interface]
Address = 10.255.0.41
PrivateKey = eDG/w5xrAzIh1JoI/LisvKmTja5T2VL/bi9oFpJQ4mc=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = H6UinmpfrCyaJI4nmpk7YzOTXBGh74y/iu4jJx/+TG8=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
