[Interface]
Address = 10.255.0.3
PrivateKey = uLiFdHoVDRio9OuPWcQrNo5HNhzoLury/Ce9nfdIcnU=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = iOLy4Zs7FdL9Mew3cJpTDOCAXh88Zn2quXGXlo+AKQ0=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
