[Interface]
Address = 10.255.0.9
PrivateKey = MK4fC8SVv2Rvrvwk/YWrU9OmtyE21rYFPeis89SsRnE=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = Any5wG5t0fiV2P6Nv+vEtusS15GCsTz3rMxv+gnSIjM=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
