[Interface]
Address = 10.255.0.33
PrivateKey = uMEQ3ASEbFDB1+1a/Uyknh1vV6zbnEvfHHapF0poMks=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = LxHw3OVy+qCXHDM0/QNXvkD2n/1vGj5fdWeK+i5bfmg=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
