[Interface]
Address = 10.255.0.32
PrivateKey = 8DxEFDZqYwuchf2F/OoT0XN+IGMg946RVcCE/M1elVQ=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = 6yaZfU66xJRijv4cG5kEVy1nkJC5g2/MyD8E2gcMmW0=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
