[Interface]
Address = 10.255.0.8
PrivateKey = iDh6xNjzRUrQHXH4+6H42xTwvBAAMdiWaOviTzQvQFM=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = J3OOcQoDgCrzOTIHl/pn+3sG4VB0no6SQe8kdf8hPXQ=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
