[Interface]
Address = 10.255.0.47
PrivateKey = +A0wQYaemdGHP55crs5llV4sPwuTbGv4OZx2BArcX2I=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = sIb80tSDKv9HY6Xdc0r6jbsMOLt6eSG7RYi5ahNljiM=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
