[Interface]
Address = 10.255.0.10
PrivateKey = OC6fvERMnfXdQgUV9crROFGn8sOOBBhKy9j/1sh6Zk0=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = wA4ms2qEr1GmbHTwd7fi8p2N00eHh0TNAIulkHIXvuE=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
