[Interface]
Address = 10.255.0.16
PrivateKey = cAQcX5JYtJ+kXYNKURhlPGEVPt43yW3Upq9yN9VBCnY=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = nzqNpOp9+WtIK4eUypeVAQJ3cf+0HZAt6tCxAo6sq8s=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
