[Interface]
Address = 10.255.0.25
PrivateKey = 8Ck48f8B7HBmKLu4IdP7e7r4ZDzbXiq9igCQ7g9tIHI=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = 4S+1x+1mDcQNGlEX6QJqT9AN5TsbZ4H4PWhfjhL+Pok=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
