[Interface]
Address = 10.255.0.34
PrivateKey = 8IHLvnVHtKXk4tPkFgBcDTw8FyWfnGa7QofD2f0ifU0=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = R9DHKMnNLtZ7gBynvIXVAqUyxorAXpm6eAISeN4HCxo=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
