[Interface]
Address = 10.255.0.35
PrivateKey = kMsl9KbpFUC+J6LW+BVuhsI+r3KSW+DZ7Wn9DRuTnHQ=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = 5msCzjdZUKgrbiBd/lU5fnbwK6zld5Xa5GxPfpva0x4=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
