[Interface]
Address = 10.255.0.44
PrivateKey = oMtkEf4niVnqbHt2OixXALsZ7mOeE9vpzC2rHzJkwEc=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = 6OP9V0/76rZlOufjsCuWW613HLaK00DhBScgK7RsPIw=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
