[Interface]
Address = 10.255.0.48
PrivateKey = 2NB0IZt8oeZ8JX0cvepqWcYe2pnos3UzAI1gbkRjuW0=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = dngLu/lIhL+TmcKV/tMGxxwKKQje6Eez4uuiQpvZb2A=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
