[Interface]
Address = 10.255.0.4
PrivateKey = yNstubWzxrjbAjoP2OTcesbse5GQ4pMmOoPpL8+7X3o=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = TTpphL1/Fk+BYQHbHHfOBU6tW7UZlLELTL6CORP8+/4=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
