[Interface]
Address = 10.255.0.27
PrivateKey = YBly19AfayONc3W0yK1fc5l00FNqsd69k9AGkLPvY3U=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = of1g+MuqF9EAjf6OrTa1qhpucNziFNL59x2A0hGsuig=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
