[Interface]
Address = 10.255.0.24
PrivateKey = AJtadkIW8TyBuUxPuJvjFkbDqTlIGXH+GyJs30aGh0U=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = 0paJsNHWmUJRmWd/RSr0WCXx4m3OAx09yq/hv96nQME=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
