[Interface]
Address = 10.255.0.12
PrivateKey = cHp08oxJEN0eEcPAFoICWIFvegCcjgOcRZFis7a1BmI=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = U474l2EcDDOYRzoCxl1i2p8S6lspyr7rllEuHTlm2fU=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
