[Interface]
Address = 10.255.0.21
PrivateKey = 2Mnx6IsS070O8P9uHTyHFeCZqnI8gkjQ8lpTMj25AWA=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = uB4xxXJ9zSGlq2zIHPvADOGeT7r89yW4oFNcVuqwRc0=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
