[Interface]
Address = 10.255.0.40
PrivateKey = SLYshumGVwz5l45ppi5vqQr9K6ZjQczGG1lZ79bxQmo=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = 7xHEdpZnmw89FMu+ZqNNT/cH4mjdbyH1wWdYmEexbeQ=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
