[Interface]
Address = 10.255.0.45
PrivateKey = 4EMiatPhF8PKVvvM6Lbuo+2RarNhOoJEBa2rz5mWQ1c=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = HziHnlfWblnbzzbvI/5pce1cAy/Mtlj0pGWqHMeoFrs=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
