[Interface]
Address = 10.255.0.2
PrivateKey = KHJB0SxL8DDaNw85NYtsAMUKIN9HbLKz0d92pQa4a3Q=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = O59u3QBq0V+kJjkVS45ClkcsTpMeE5r8pt/LPw7vJEk=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
