[Interface]
Address = 10.255.0.11
PrivateKey = aKyRnMtW63NbcvlgQcWIwvlXzFAr5Ht7Qmzx092Al2Y=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = kfv4pW7QQbNcJhfaBfBPz7MvbWOVj8DkNoLFk4E6pcw=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
