[Interface]
Address = 10.255.0.6
PrivateKey = yGxRX3Ny29BwK5CEdFWJkE5UG0r+F92m6H8pyQhIfX0=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = V6w8FZuTunv13RoY1Kb5JoioWtFSu1Ka5J06AGgddcc=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
