[DEFAULT]
# URL Base do Mikrogestor (ex: http://localhost:3000 ou https://mikrogestor.com.br)
API_URL = http://localhost:3000

# Sua API Key gerada no dashboard do Mikrogestor
API_KEY = COLE_SUA_API_KEY_AQUI

# Seu subdomínio (slug)
SUBDOMAIN = meupontodevenda

# Pasta local que o script deve monitorar
WATCH_PATH = ./monitorar
