[Interface]
Address = 10.255.0.31
PrivateKey = MItjZDJ1Yla4KPY++b0Z2ZqbAx5G08qIasY8yj90nVQ=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = 83rq0HnxlypamItKZg3uY6ahrAvZhm2xaR7gb3ueiHI=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
