[Interface]
Address = 10.255.0.43
PrivateKey = WCvY9tODJ4OMd3gg788y7BF6EuMm9zKJakJ4lw+zXEo=
ListenPort = 51820
DNS = 10.255.0.1

[Peer]
PublicKey = HKz1xJ+MRSAqOCr+IesyyHZQyOFOTtyXr1sMWo2V8TU=
PresharedKey = 8fv4FqKNHEngq/6F6K8FzXXXwtvpezPWDw46Gy6CBAY=
Endpoint = 45.71.105.254:51820
AllowedIPs = 0.0.0.0/0, ::/0
